FROM node:23.1.0-bookworm-slim AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:23.1.0-alpine

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=build /app/build /app/build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build"]
