FROM python:3.11-alpine AS build

WORKDIR /app

COPY requirements.txt .

RUN apk add --no-cache ca-certificates

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "main:main_app"]
